# Generated by Django 2.2 on 2021-02-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='item',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
